# Generated by Django 3.2.7 on 2021-09-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210909_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_thumb',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
